### ISSUE TITLE
Remove fbid from facebook links?

### ISSUE THREAD

**Issue by cgcgcgcgcg** [apiraino/link_cleaner#10]
Can you remove those terrible fbid things from links?
Imagus extension used to work fine on facebook pics before fbid was enforced.

**Comment by apiraino** [comment]
Hey, thanks for reminding me about this, this is definitively something to do!

Would you kindly post a comment here with some example links to be used as a test case. You'll spare me some time :-) and they will be [added here](https://github.com/apiraino/link_cleaner/blob/dd0c02e00dbc88b7b7fcbf6064b03ebff1bde186/test_urls.html#L42).

**Comment by cgcgcgcgcg** [comment]
Here's a simple example:
https://www.facebook.com/photo.php?fbid=1349087945249015&set=a.106434256181063&type=3

I don't know if an extension fixes this in real-time yet -most extensions handle links after you click them- but the fbid thing also makes photos in comments (and group comments) not "readable" by the Imagus extension.
That means when you hover on them the full pic in large size doesn't show up any more.

**Comment by apiraino** [comment]
Well, this is something slightly different, in my opinion: you're visiting a Facebook page therefore you receive a lot of other assets in addition to the actual photo. In this case the `fbid` parameter is not tracking, it's essential to get to the right page. There's no way you can isolate the photo from the rest of the content you get (unless going through hoops and parsing the HTML, which is not a job for Link Cleaner).

Link Cleaner should clean (for example) links *outside facebook* that have a facebook tracker parameter.

Makes sense?

**Comment by cgcgcgcgcg** [comment]
Yes, thank you.
I know that the developer of Imagus should be the one figuring this out since hovering a facebook link containing fbid is Imagus's job not Link Cleaner +'s.
