### ISSUE TITLE
Feature Request: Clean Google redirect links

### ISSUE THREAD

**Issue by SaltyBet** [apiraino/link_cleaner#22]
Example link:

https://www.google.com/url?q=https%3A%2F%2Fsome.site.foo%2Fbar%2Fbaz%2F&sa=D&sntz=1&usg=NSDwPAU2iD3B-swylVPimfUMevWiUaWbMN

Clean link:

https://some.site.foo/bar/baz

**Comment by apiraino** [comment]
Hi, thanks for opening this issue.

Actually, I think it's a bug (or regression) because we should already [manage google urls](https://github.com/apiraino/link_cleaner/blob/5a60fc9dba2459fae80aa9c7a372b3b7c3bb8077/background.js#L235).

I'll check what's happening

**Comment by apiraino** [comment]
Fixed and published in v1.7.3

thanks @SaltyBet
