### ISSUE TITLE
Prevent Firefox from adding unclean URLs to browser history

### ISSUE THREAD

**Issue by ghost** [apiraino/link_cleaner#27]
If you visit https://www.aliexpress.com/item/Mountainskin/32947508308.html?useless_param=kill_me&utm_source=hahaha then you will find in your browser history the following entries:
- [older urls]
- https://www.aliexpress.com/item/Mountainskin/32947508308.html?useless_param=kill_me&utm_source=hahaha
- https://www.aliexpress.com/item/Mountainskin/32947508308.html?useless_param=kill_me
- https://www.aliexpress.com/item/32947508308.html
- [newer urls]

This is not desirable behaviour.

**Comment by Riamse** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest doesn't seem to have any advice.

**Comment by apiraino** [comment]
Yes, I see it difficult blocking these spurious entries from being recorded. The event `onBeforeRequest` is as early as we can do anything so I guess the history entry is added even earlier. 
The only way I could find is to manually remove them, one by one. There's an [api to handle history](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history) but it requires an additional permission.

I am afraid that requesting such API would scare our users :-)

**Comment by apiraino** [comment]
[CleanURLs](https://gitlab.com/KevinRoebert/ClearUrls), another - more advanced - links cleaner does it by using [the History replace_state API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method)
