### ISSUE TITLE
Feature Request: Support Firefox for Android (Fenix)

### ISSUE THREAD

**Issue by mhio** [apiraino/link_cleaner#29]
It looks like addons for the latest version of Firefox for Android are being allowed in a more strict fashion by Mozilla.  

I haven't looked into what is required now, but I'll add updates when I find out what the process is.

**Comment by mhio** [comment]
Looks like it's more on the Firefox end... They initially only built out the web extension API's for a [shortlist of add ons](https://github.com/mozilla-mobile/fenix/issues/5315#issuecomment-583710384). 

Only the nightly build of Firefox for Android [will allow loading of any add for the moment](https://github.com/mozilla-mobile/fenix/issues/13059). 

They will publish any addon updates on [their blog](https://blog.mozilla.org/addons/category/mobile/)

**Comment by mhio** [comment]
I'll try adding it in the nightly build and see how it goes

**Comment by qoheniac** [comment]
Just a short feedback for anyone interested: I tested the add-on with Fennec F-Droid 100.1.1 on Android 11 (Lineage OS for MicroG) and it works perfectly fine.
