### ISSUE TITLE
How to whitelist?

### ISSUE THREAD

**Issue by Ugo-Gira** [apiraino/link_cleaner#33]
Hi, I found no other way to ask this, neither here nor on the Firefox Add-on page.
I wish to be able to whitelist a domain when it occurs that the add-on breaks a link.
How?
Thanks

**Comment by apiraino** [comment]
Hi, it's fine to open issues for questions.

Currently no concept of whitelist/blacklist is implemented in the add-on. If you see the add-on breaks something, feel free to open an issue (or provide a patch to fix).

thanks

**Comment by Ugo-Gira** [comment]
And what does it mean "clean AMP links in the (very minimalist) settings?

**Comment by apiraino** [comment]
[AMP links](https://en.wikipedia.org/wiki/Accelerated_Mobile_Pages) are google's attempt to provide mobile-friendly pages, Basically it works by having the content provider create a reduced version of the page. You can see examples of AMP pages in our [test file](https://github.com/apiraino/link_cleaner/blob/d7c32c91227dfcb9b4fafbccf5a7d1de7fb89ee3/test_urls.html#L54-L60). 

I agree this could be better explicited, I'll push an update to the README :+1:

**Comment by U-Go-7** [comment]
Ah, so it's only for mobile devices. I have you on Desktop, so, I do not need that.
Thanks
