### ISSUE TITLE
Feature request: cleaning Twitter source links

### ISSUE THREAD

**Issue by ZacharyTalis** [apiraino/link_cleaner#37]
**Description:**

Twitter URLs, when visited directly, are formatted like -

[https://twitter.com/HugeNintendoDS/status/1386171485417623552](https://twitter.com/HugeNintendoDS/status/1386171485417623552)

When clicking on `Share button > Copy link to Tweet`, an additional source tag is appended -

[https://twitter.com/HugeNintendoDS/status/1386171485417623552?s=20](https://twitter.com/HugeNintendoDS/status/1386171485417623552?s=20)

This tag introduces a pestersome `More Tweets` section that replaces replies with algorithmically-suggested tweets."

**Suggested implementation:**

Introduce off-by-default link cleaning for Twitter links that redirects tag-appended URLs to their tagless counterparts.

If possible, stop Twitter from inserting a source tag when `Copy[ing] link to Tweet`.

**Of note**:

* The number following `s=` varies by client.
* I'd contribute the PR myself, but I'm bad at regex 😢

**Comment by apiraino** [comment]
closed by #40
