### ISSUE TITLE
Publish the extension

### ISSUE THREAD

**Issue by apiraino** [apiraino/link_cleaner#5]
merging upstream is not feasable, therefore we need a new extension on [AMO](https://addons.mozilla.org/en-US/firefox/)

Suggestions for the name? LinkCleaner+? LinkCleanerNew?

**Comment by lackaff** [comment]
Glad to see this happening. LinkCleaner+ sounds good to me. 

(Or PurifyLink? LinkCleanser? URLSanitizer? LinkDisinfect? :)

**Comment by apiraino** [comment]
ok @lackaff the extension has been published, we just to need to wait for the review to happen.

Thanks for pushing me to get this done ^_^

**Comment by Riamse** [comment]
Good to hear! What was the name you settled on in the end?

(Sorry for the absence from development, I've been doing
non-software-engineering work as of late and kinda stopped coding in
general as a result)

**Comment by lackaff** [comment]
@apiraino Awesome, and thank you! Fingers crossed for a speedy review.

**Comment by apiraino** [comment]
@Riamse we decided for `Link Cleaner+`, which sounds nice :)

And no worries, the project is always open for contribution, so feel free to come back whenever you want. And thank you for your help!
